Dfldb
dark-matter-interactive/dark-matter-disco pull request #71
Opened 2019-06-21 21:30 UTC by RayMan504

setup helpers for database User and Friend request database queries. setup express routers for users and friend requests

2019-06-21 21:33 UTC, chusto2 approved these changes

2019-06-21 22:00 UTC, jesseLessinger requested changes

2019-06-21 22:00 UTC, jesseLessinger commented on dark-matter-disco/database-postgres/helpers.js
> +    return success[0].id
why return only the id and not the whole user?

2019-06-21 22:00 UTC, jesseLessinger commented on dark-matter-disco/database-postgres/helpers.js
> +    .then(data => data);
does this .then do anything?

2019-06-21 22:00 UTC, jesseLessinger commented on dark-matter-disco/database-postgres/helpers.js
> +  return User.findAll({ where: { id } }).then(data => data);
does findAll return an array? why not just find or findOne which ever it is in sequelize

2019-06-21 22:00 UTC, jesseLessinger commented on dark-matter-disco/database-postgres/helpers.js
> +  return Friends.findAll({ where: { userId, status: 0 }}).then(pendingRequests => pendingRequests);
i think you have to match the userId that coming in as a param, with the friendId in the friends table, a pending request is a request made by someone else to me

2019-06-21 22:00 UTC, jesseLessinger commented on dark-matter-disco/database-postgres/helpers.js
> +}
this looks good, but do we also need to add the second entry with the friend relationship going the other way

2019-06-21 22:00 UTC, jesseLessinger commented on dark-matter-disco/server/routes/friends.js
> +    getPendingRequests(1).then((results) => {
this can't be hardcoded

2019-06-21 22:00 UTC, jesseLessinger commented on dark-matter-disco/server/routes/friends.js
> +    storeFriendRequest(1, 2);
make dynamic too

2019-06-21 22:00 UTC, jesseLessinger commented on dark-matter-disco/server/routes/friends.js
> +      acceptFriendRequest(1, 2);
dynamic

2019-06-21 22:00 UTC, jesseLessinger commented on dark-matter-disco/server/routes/users.js
> +  getUserById(2).then((result) => {
dynamic

2019-06-21 22:00 UTC, jesseLessinger commented on dark-matter-disco/src/app/dance-floor/dance-floor.component.ts
> +      socketService.emit('pose', poses, 'James');
can't mess with code like this any push it up

2019-06-21 22:03 UTC, RayMan504 commented on dark-matter-disco/database-postgres/helpers.js
> +    .then(data => data);
yes. I need to return a single user once the client initiates a get request

2019-06-22 00:16 UTC, RayMan504 commented on dark-matter-disco/database-postgres/helpers.js
> +}
I added the second call so that so that both friend relationships are updated in the database

2019-06-24 14:33 UTC, jesseLessinger approved these changes

2019-06-24 14:33 UTC, merged